### ISSUE TITLE
infinite loop with specific values

### ISSUE THREAD

**Issue by iperov** [francisengelmann/fast_voxel_traversal#5]
now I checked in C++ your file, its dead loop

_bin_size = 16;
Eigen::Vector3d ray_start(-668, -340, 77); 
Eigen::Vector3d ray_end(404, -64, -784);

**Comment by iperov** [comment]
its look like accumulating double-error result error in final 1 step.

**Comment by wangx1996** [comment]
@iperov hello， did you solve that？
